language: node_js
node_js:
  - "4.0"
sudo: false
addons:
  code_climate:
    repo_token: 5d23522c61a9a3eef235dcd9c53cf6b1f2d74a5c45e723a0f3feb5f34650785b
script: "npm run cov"
after_script:
  - codeclimate-test-reporter < etc/lcov.info
